version: 1.0
description: YAVS security baseline for src/ directory
created_date: 2025-11-11
notes: |
  This baseline was created from a clean scan of src/ with 0 findings.
  Any new findings detected in future scans will cause the PR workflow to fail.

  Scanners used:
  - Trivy (dependencies, secrets, licenses)
  - Semgrep (SAST)
  - Bandit (Python security)
  - Checkov (IaC compliance)

  To update this baseline:
  1. Run: yavs scan src/ --all --no-ai -o results.json --continue-on-error
  2. Review findings and create suppressions as needed
  3. Export: yavs ignore export results.json -o .yavs-baseline.yaml

suppressions: []
